[2025-09-28T00:13:32.533+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-28T00:13:32.542+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_forecast_stock_robust.create_or_replace_model scheduled__2025-09-27T00:00:00+00:00 [queued]>
[2025-09-28T00:13:32.544+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_forecast_stock_robust.create_or_replace_model scheduled__2025-09-27T00:00:00+00:00 [queued]>
[2025-09-28T00:13:32.545+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-28T00:13:32.550+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_or_replace_model> on 2025-09-27 00:00:00+00:00
[2025-09-28T00:13:32.553+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=29995) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-28T00:13:32.554+0000] {standard_task_runner.py:64} INFO - Started process 29997 to run task
[2025-09-28T00:13:32.554+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_forecast_stock_robust', 'create_or_replace_model', 'scheduled__2025-09-27T00:00:00+00:00', '--job-id', '427', '--raw', '--subdir', 'DAGS_FOLDER/ml_forecast_stock.py', '--cfg-path', '/tmp/tmpsnq9q60s']
[2025-09-28T00:13:32.555+0000] {standard_task_runner.py:91} INFO - Job 427: Subtask create_or_replace_model
[2025-09-28T00:13:32.575+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_forecast_stock_robust.create_or_replace_model scheduled__2025-09-27T00:00:00+00:00 [running]> on host 11e1994bdecf
[2025-09-28T00:13:32.618+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data226' AIRFLOW_CTX_DAG_ID='ml_forecast_stock_robust' AIRFLOW_CTX_TASK_ID='create_or_replace_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-27T00:00:00+00:00'
[2025-09-28T00:13:32.619+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-28T00:13:32.630+0000] {base.py:84} INFO - Using connection ID 'snowflake_default' for task execution.
[2025-09-28T00:13:32.631+0000] {connection.py:408} INFO - Snowflake Connector for Python Version: 3.11.0, Python Version: 3.12.4, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-09-28T00:13:32.631+0000] {connection.py:1258} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-09-28T00:13:33.479+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-09-28T00:13:33.845+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-09-28T00:13:33.963+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-09-28T00:13:33.963+0000] {ml_forecast_stock.py:223} INFO - Using: warehouse="BEETLE_QUERY_WH", database="ASH_DB", schema="STOCK_SCHEMA"
[2025-09-28T00:13:34.102+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-09-28T00:13:34.102+0000] {ml_forecast_stock.py:231} INFO - Executing SQL statement 1/1
[2025-09-28T00:30:49.024+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /queries/01bf576e-0306-8759-000f-c0df002a6e32/result?request_guid=ed8fa429-c22a-4c86-834a-becc10e74cbc
[2025-09-28T00:30:49.483+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-09-28T00:30:49.580+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-09-28T00:30:49.581+0000] {ml_forecast_stock.py:237} INFO - All SQL statements executed successfully
[2025-09-28T00:30:49.582+0000] {connection.py:773} INFO - closed
[2025-09-28T00:30:49.670+0000] {connection.py:779} INFO - No async queries seem to be running, deleting session
[2025-09-28T00:30:49.733+0000] {ml_forecast_stock.py:306} INFO - ML Forecast model created successfully
[2025-09-28T00:30:49.735+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-28T00:30:49.736+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-28T00:30:49.759+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ml_forecast_stock_robust, task_id=create_or_replace_model, run_id=scheduled__2025-09-27T00:00:00+00:00, execution_date=20250927T000000, start_date=20250928T001332, end_date=20250928T003049
[2025-09-28T00:30:49.823+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-28T00:30:49.867+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-28T00:30:49.869+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
